

var svg= d3.select('body').append('svg')

    .style('border', '2px solid')
    .attr('width',10000)
    .attr('height', 10000)

d3.select('svg')
.append('line')
    .attr('x1', 0)
    .attr('y1', 1500)
    .attr('x2',4999)
    .attr('y2',1500)
    .style('stroke', 'black')
    .style('stroke-width', 1)

d3.select('svg')
.append('rect')
    .attr('height', 100)
    .attr('width', 116)
    .attr('x', 0)
    .attr('y', 1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height',100)
    .attr('width', 2)
    .attr('x',0 )
    .attr('y', 1450)
    .style('fill', 'green')
    .style('stroke', 'green')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height', 100)
    .attr('width',126 )
    .attr('x', 1927)
    .attr('y', 1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height', 100)
    .attr('width',225)
    .attr('x',2190 )
    .attr('y', 1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height', 100)
    .attr('width', 154 )
    .attr('x', 2251 )
    .attr('y', 1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height',100)
    .attr('width', 1348)
    .attr('x', 2465)
    .attr('y',1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height',100)
    .attr('width', 254)
    .attr('x', 3880) 
    .attr('y',1450)
    .style('fill', 'black')
    .style('stroke', 'black')
    .style('stroke-width',10)
d3.select('svg')
.append('rect')
    .attr('height',100)
    .attr('width', 3)
    .attr('x', 4137)
    .attr('y',1450)
    .style('fill', 'red')
    .style('stroke', 'red')
    .style('stroke-width',10)